In [4]:
import numpy as np

zero_array = np.zeros(10, dtype='int32')
zero_array[4] = 7
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[0 0 0 0 7 0 0 0 0 0]
int32 (10,)


In [5]:
import numpy as np

sequence_array = np.arange(10,25)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
int32 (15,)


In [8]:
import numpy as np

array1 = np.arange(7,17)
array2 = array1.reshape(2, -1)
print('array2.shape:', array2.shape)
print(array2)

array2.shape: (2, 5)
[[ 7  8  9 10 11]
 [12 13 14 15 16]]


In [22]:
import numpy as np
 
np.random.randint(0, 9, (3,3))

array([[5, 1, 0],
       [3, 3, 1],
       [8, 1, 8]])

In [25]:
import numpy as np

np.random.random((3,3,3))

array([[[0.12582949, 0.55936485, 0.96731627],
        [0.44949975, 0.01535319, 0.91899981],
        [0.92971729, 0.33195528, 0.56973107]],

       [[0.39186207, 0.76931926, 0.26843433],
        [0.78319287, 0.00160609, 0.34311788],
        [0.03500076, 0.94379081, 0.19881258]],

       [[0.53685965, 0.19369873, 0.50698833],
        [0.90311906, 0.41895485, 0.53079937],
        [0.25135321, 0.13299312, 0.9821038 ]]])

In [31]:
import numpy as np

array1 = np.random.randint(0,10, (1, 12))
array2 = np.sort(array1)
print(array2)

[[0 2 2 3 3 5 5 5 6 7 8 8]]


In [35]:
import numpy as np

array1 = np.random.randint(0, 101, (5, 6))
print(array1)

[[ 0 40 62 12 47 93]
 [20 51 60 14  7 79]
 [21 78 38 32 96 75]
 [46 40 16 71 43 56]
 [70 38 51 87 76 40]]
